### ISSUE TITLE
Tracking: React Native SDK v1.0

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native-old#11]
### Requirements

Create a  `xmtp-react-native` that mirrors `xmtp-js` functionality and demonstrate core functionality in a React Native sample app.

### Prerequisites  

- [x] `ios-xmtp` as a cocoapod
    - [ ] swift-gRPC does not support cocoapods so needs to be replaced with rust
    - [ ] GigaBitcoin/secp256k1 does not support cocoapods so needs to be replaced with rust
    - [ ] SwiftNIO does not support cocoapods so needs to be replaced with rust

### Developer Preview

- [ ] Create a native bridge to iOS and Android
    - [ ] Add authentication to match xmtp-js
    - [ ] Wrap xmtp in a`xmtp.Client` (like `xmtp-js`)
    - [ ] Reproduce utility classes/methods
        - [ ] Client
        - [ ] ConversationV1
        - [ ] ConversationV2
        - [ ] Conversations
        - [ ] MessageV1
        - [ ] MessageV2
        - [ ] PrivateKey
        - [ ] PublicKey
        - [ ] PrivateKeyBundleV1
        - [ ] PrivateKeyBundleV2
        - [ ] PublicKeyBundle
        - [ ] SignedPublicKeyBundle
        - [ ] Stream
        - [ ] TextCodec
        - [ ] CompositeCodec
        - [ ] StreamAllMessages
        - [ ] AttachmentCodec
    - [ ] Publish npm library https://reactnative.dev/docs/native-modules-setup
- [ ] Publish repo README covering Dev Preview features and with Dev Preview badge

### GA

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA

### Nice to have

- [ ] Create example app
    - [ ] Use xmtp-react-native to demonstrate SDK
        - [ ] Initialize client with a signer
        - [ ] List conversations
        - [ ] List messages
        - [ ] Send messages
        - [ ] Stream conversations
        - [ ] Stream messages
        - [ ] Wallet Connect
         
### Decision log

[April 12, 2023] 
- In an effort to move the xmpt-iOS SDK into a cocoapod to support the native bridge we will be making an effort to pull unsupported cocoapod support into a rust library. You can read more about React Native Bridge and Swift Package Manager here: https://github.com/react-native-community/discussions-and-proposals/issues/587
- As a stop gap we will be releasing a new [react native quick starter app ](https://github.com/xmtp/xmtp-quickstart-react-native) that shows a simple webview implementation that calls through to `xmpt-js`.
